import fs from 'node:fs';
import path from 'node:path';
import { OcrUnavailableError } from '../../common/errors.js';

/**
 * OCR provider interface + registry. Providers declare which MIME types
 * they support and an `isAvailable()` probe.
 *
 * The registry ships two providers:
 *   - PlainTextOcrProvider  (always available, zero cost)
 *   - TesseractJsOcrProvider (real image OCR; needs `tesseract.js` installed
 *     AND Tesseract language data present — see `npm run ocr:setup`)
 *
 * Language data is deliberately resolvable from a LOCAL directory so OCR keeps
 * working with no network at all (offline demo, flaky venue wifi). Run
 * `npm run ocr:setup` once on a connected machine to vendor `eng.traineddata.gz`
 * into `backend/data/ocr-lang/`.
 */

/** Default location of vendored Tesseract language data. */
export const DEFAULT_LANG_DIR = path.resolve(
  path.dirname(new URL(import.meta.url).pathname),
  '../../../data/ocr-lang',
);

/** Tesseract language data is served gzipped from the CDN by default. */
const DEFAULT_LANG_CDN = 'https://tessdata.projectnaptha.com/4.0.0';

export class PlainTextOcrProvider {
  name = 'plain-text';

  supports(mimeType) {
    return (
      mimeType === 'text/plain' ||
      mimeType === 'text/markdown' ||
      mimeType === 'text/csv' ||
      mimeType === 'application/json' ||
      mimeType === 'text'
    );
  }

  async isAvailable() {
    return true;
  }

  /** Human-readable reason when unavailable; null when available. */
  async unavailabilityReason() {
    return null;
  }

  async extract({ buffer }) {
    if (!buffer || typeof buffer.toString !== 'function') {
      throw new OcrUnavailableError('No readable file content was provided');
    }
    let text = '';
    try {
      text = buffer.toString('utf8');
    } catch {
      throw new OcrUnavailableError('File could not be decoded as text');
    }
    if (text.length > 500_000) text = text.slice(0, 500_000);
    // Allow common unicode whitespace/control pictures; reject binary blobs.
    const sample = text.slice(0, 50_000).replace(/\0/g, '');
    if (sample.length !== text.slice(0, 50_000).length) {
      throw new OcrUnavailableError('File does not look like plain text');
    }
    const printable = /^[\x09\x0A\x0D\x20-\x7E\u00A0-\uFFFF]*$/.test(sample);
    if (!printable) {
      throw new OcrUnavailableError('File does not look like plain text');
    }
    return { text: text.replace(/\0/g, ''), confidence: 1.0, provider: this.name };
  }
}

/**
 * Best-effort text extraction from digital (text-based) PDFs.
 *
 * No dependency, no network: lab-report PDFs generated by a computer store
 * their text as literal `(...)` and hex `<...>` strings in content streams,
 * which this provider decodes directly. Scanned-image PDFs carry no text
 * layer and still fail gracefully with paste-text guidance — that failure is
 * an honest OcrUnavailableError, never a crash and never garbage.
 */
export class PdfTextOcrProvider {
  name = 'pdf-text';

  supports(mimeType) {
    return mimeType === 'application/pdf';
  }

  async isAvailable() {
    return true;
  }

  async unavailabilityReason() {
    return null;
  }

  async extract({ buffer }) {
    if (!buffer || typeof buffer.length !== 'number' || buffer.length === 0) {
      throw new OcrUnavailableError('The uploaded PDF is empty or unreadable.');
    }
    let text = '';
    try {
      text = extractPdfText(buffer);
    } catch (e) {
      throw new OcrUnavailableError(
        `This PDF could not be read automatically (${e?.message || 'parse error'}) — open the PDF, copy its text, ` +
          `and paste it into the upload dialog. Your report is saved and nothing is lost.`,
      );
    }
    if (!looksLikeReportText(text)) {
      // Scanned-image PDF (no text layer) or an unreadable file.
      throw new OcrUnavailableError(
        'This PDF has no readable text layer (it looks like a scanned image) — open the PDF, copy its text if you can, ' +
          'and paste it into the upload dialog (or add the values manually). Your report is saved and nothing is lost.',
      );
    }
    return { text, confidence: 0.7, provider: this.name };
  }
}

/**
 * Decodes the text layer of a PDF buffer (literal + hex strings).
 * Best-effort: never throws on malformed input — returns '' instead.
 */
export function extractPdfText(buffer) {
  try {
    const bytes = Buffer.isBuffer(buffer) ? buffer : Buffer.from(buffer);
    if (bytes.length < 5 || bytes.subarray(0, 5).toString('latin1') !== '%PDF-') return '';
    // Cap the scan: content beyond a few MB is not a lab report's text layer.
    const raw = bytes.subarray(0, Math.min(bytes.length, 6 * 1024 * 1024)).toString('latin1');
    // Reconstruct lines from the content stream's own line breaks: generators
    // typically emit one text row per stream line (words of a row share the
    // line as several Tj ops). Strings on one stream line join with a space;
    // stream lines become text lines — the shape the extractor expects.
    // (No coordinate/layout parsing: multi-column PDFs may interleave.)
    const outLines = [];
    const streamLines = raw.split(/\r?\n/).slice(0, 20000);
    for (const streamLine of streamLines) {
      const parts = [];
      const literalRe = /\((?:\\.|[^\\()])*\)/g;
      let m;
      let count = 0;
      while ((m = literalRe.exec(streamLine)) !== null && count < 1000) {
        count += 1;
        parts.push(decodePdfLiteral(m[0].slice(1, -1)));
      }
      const hexRe = /<([0-9A-Fa-f\s]{4,})>/g;
      count = 0;
      while ((m = hexRe.exec(streamLine)) !== null && count < 1000) {
        count += 1;
        const decoded = decodePdfHex(m[1]);
        if (decoded) parts.push(decoded);
      }
      const joined = parts.join(' ').replace(/\s+/g, ' ').trim();
      if (joined) outLines.push(joined.slice(0, 2000));
      if (outLines.length >= 2000) break;
    }

    return outLines.join('\n').trim().slice(0, 100_000);
  } catch {
    return '';
  }
}

function decodePdfLiteral(inner) {
  return inner.replace(/\\(.)/gs, (match, ch) => {
    switch (ch) {
      case 'n': return '\n';
      case 'r': return '\n';
      case 't': return ' ';
      case '(': return '(';
      case ')': return ')';
      case '\\': return '\\';
      default:
        if (/[0-7]/.test(ch)) return ''; // octal escape — drop
        return ch;
    }
  });
}

function decodePdfHex(hex) {
  try {
    const clean = hex.replace(/\s+/g, '');
    if (clean.length < 2 || /[^0-9A-Fa-f]/.test(clean)) return '';
    const padded = clean.length % 2 === 0 ? clean : `${clean}0`;
    const buf = Buffer.from(padded, 'hex');
    // UTF-16BE BOM → decode as UTF-16; otherwise latin1.
    if (buf.length >= 2 && buf[0] === 0xfe && buf[1] === 0xff) {
      return buf.subarray(2).swap16().toString('utf16le');
    }
    return buf.toString('latin1');
  } catch {
    return '';
  }
}

/** Acceptance gate: enough printable, letter-and-digit-bearing text to be a report. */
function looksLikeReportText(text) {
  if (typeof text !== 'string' || text.length < 30) return false;
  const letters = (text.match(/[A-Za-z]/g) || []).length;
  const digits = (text.match(/[0-9]/g) || []).length;
  if (letters < 10 || digits < 2) return false;
  const printable = text.replace(/[\x09\x0A\x0D\x20-\x7E\u00A0-\uFFFF]/g, '');
  return printable.length / text.length < 0.05;
}

/**
 * Tesseract.js-backed image OCR.
 *
 * The worker is created once and reused: Tesseract worker startup (WASM init +
 * language model load) dominates per-scan latency, so caching it turns repeat
 * scans from seconds into sub-second work. Call `terminate()` on shutdown.
 */
export class TesseractJsOcrProvider {
  name = 'tesseract.js';

  /**
   * @param {object} [opts]
   * @param {string} [opts.lang='eng']
   * @param {string|null} [opts.langDir] directory holding `<lang>.traineddata[.gz]`;
   *   when the file is absent we fall back to the public CDN.
   * @param {number} [opts.oem=1] LSTM engine mode
   * @param {number} [opts.probeTtlMs=60000] how long a CDN verdict is cached
   * @param {number} [opts.probeTimeoutMs=4000] HEAD-probe network timeout
   * @param {number} [opts.workerTimeoutMs=60000] worker-startup timeout: a
   *   HEAD-reachable CDN can still stall the multi-MB language download, and
   *   a hung worker must fail fast with guidance, never hang the request.
   */
  constructor({ lang = 'eng', langDir = DEFAULT_LANG_DIR, oem = 1, probeTtlMs = 60_000, probeTimeoutMs = 4_000, workerTimeoutMs = 60_000 } = {}) {
    this.lang = lang;
    this.langDir = langDir;
    this.oem = oem;
    this.probeTtlMs = probeTtlMs;
    this.probeTimeoutMs = probeTimeoutMs;
    this.workerTimeoutMs = workerTimeoutMs;
    this._workerPromise = null;
    this._probe = null; // cached CDN reachability verdict
  }

  supports(mimeType) {
    return /^image\/(png|jpe?g|bmp|webp|tiff?)$/.test(mimeType || '');
  }

  /** Resolves the vendored language-data file, or null to use the CDN. */
  resolveLocalLangData() {
    if (!this.langDir) return null;
    for (const gz of [true, false]) {
      const file = path.join(this.langDir, `${this.lang}.traineddata${gz ? '.gz' : ''}`);
      if (fs.existsSync(file)) return { file, gzip: gz };
    }
    return null;
  }

  /** Tesseract `langPath` + `gzip` options derived from local data or the CDN. */
  langOptions() {
    const local = this.resolveLocalLangData();
    if (local) return { langPath: this.langDir, gzip: local.gzip };
    return { langPath: DEFAULT_LANG_CDN, gzip: true };
  }

  /** Is the `tesseract.js` module resolvable? */
  async moduleAvailable() {
    try {
      await import('tesseract.js');
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Available when the module resolves AND language data is reachable
   * (vendored locally, or the CDN is reachable). Probing the CDN avoids
   * surfacing a cryptic `fetch failed` to the user mid-scan.
   *
   * The CDN verdict is cached (see `probeTtlMs`): re-probing the network on
   * every upload would add latency to each scan and make an offline venue
   * fail slowly instead of instantly. Vendored data short-circuits entirely —
   * no network is touched at all in that case.
   */
  async unavailabilityReason() {
    if (!(await this.moduleAvailable())) {
      return 'the tesseract.js dependency is not installed (run `npm install`)';
    }
    if (this.resolveLocalLangData()) return null; // offline-capable: vendored data present

    const fresh = this._probe && Date.now() - this._probe.at < this.probeTtlMs;
    if (!fresh) {
      let reason = null;
      try {
        const res = await fetch(`${DEFAULT_LANG_CDN}/${this.lang}.traineddata.gz`, {
          method: 'HEAD',
          signal: AbortSignal.timeout(this.probeTimeoutMs),
        });
        if (!res.ok) reason = `language data responded ${res.status} from ${DEFAULT_LANG_CDN}`;
      } catch (e) {
        reason =
          `no language data vendored in ${this.langDir} and ${DEFAULT_LANG_CDN} is unreachable ` +
          `(${e?.cause?.code || e?.message || 'network error'}) — run \`npm run ocr:setup\` to vendor it for offline use`;
      }
      this._probe = { at: Date.now(), reason };
    }
    return this._probe.reason;
  }

  async isAvailable() {
    return (await this.unavailabilityReason()) === null;
  }

  /**
   * Spawns the underlying tesseract.js worker. Split out as a seam so tests
   * can stub it without spawning real worker threads.
   */
  async _createWorker() {
    const { createWorker } = await import('tesseract.js');
    // NOTE: tesseract.js re-throws every job rejection as an UNCAUGHT
    // exception unless an `errorHandler` is provided (see its
    // createWorker `onMessage`: `throw Error(data)` on reject). The
    // promise from `recognize()` still rejects normally, so a no-op
    // handler keeps failures catchable instead of crashing the process.
    return createWorker(this.lang, this.oem, {
      ...this.langOptions(),
      errorHandler: () => {},
    });
  }

  /** Lazily creates and caches the Tesseract worker. */
  worker() {
    if (!this._workerPromise) {
      this._workerPromise = (async () => {
        const pending = this._createWorker();
        let timer;
        const timeout = new Promise((_, reject) => {
          timer = setTimeout(
            () => reject(new Error(`OCR engine startup timed out after ${this.workerTimeoutMs}ms`)),
            this.workerTimeoutMs,
          );
          timer.unref?.();
        });
        try {
          return await Promise.race([pending, timeout]);
        } catch (e) {
          // Don't leak the orphaned worker if it eventually resolves.
          pending.then(
            (w) => w?.terminate?.().catch(() => {}),
            () => {},
          );
          throw e;
        } finally {
          clearTimeout(timer);
        }
      })().catch((err) => {
        this._workerPromise = null; // allow a retry after a transient failure
        throw err;
      });
    }
    return this._workerPromise;
  }

  async extract({ buffer }) {
    if (!buffer || (typeof buffer.length === 'number' && buffer.length === 0)) {
      throw this.wrapFailure('empty image buffer', 'could not read text from this image');
    }
    let worker;
    try {
      worker = await this.worker();
    } catch (e) {
      throw this.wrapFailure(e, 'the OCR engine failed to start');
    }
    try {
      const result = await worker.recognize(buffer);
      const data = result?.data || {};
      const text = typeof data.text === 'string' ? data.text : '';
      const rawConf = Number(data.confidence);
      const confidence = Number.isFinite(rawConf) ? Math.min(1, Math.max(0, rawConf / 100)) : null;
      return { text, confidence, provider: this.name };
    } catch (e) {
      throw this.wrapFailure(e, 'could not read text from this image');
    }
  }

  /**
   * Normalizes ANY tesseract failure shape into an actionable Error.
   * The worker script rejects with plain STRINGS (`err.toString()`), not
   * Error objects — reading `.message` off those yields `undefined`, which
   * used to surface as an empty `preview.note` and a missing badge
   * `ocrError`. Every failure now carries recovery guidance instead.
   */
  wrapFailure(err, what) {
    const detail = typeof err === 'string' ? err : err?.message || String(err);
    return new OcrUnavailableError(
      `Image OCR ${what}: ${detail}. ` +
        `To read photo/image reports install language data with \`npm run ocr:setup\`, ` +
        `or paste the report text into the upload dialog.`,
    );
  }

  /** Releases the cached worker (call on process shutdown). */
  async terminate() {
    if (!this._workerPromise) return;
    const p = this._workerPromise;
    this._workerPromise = null;
    // If startup is still in flight (e.g. a stalled language download),
    // don't block shutdown on it — cap the wait, and terminate the orphan
    // late if it ever resolves. (Double-terminate is safe: tesseract's
    // terminate() is idempotent.)
    p.then(
      (w) => w?.terminate?.().catch(() => {}),
      () => {},
    );
    try {
      const worker = await Promise.race([
        p,
        new Promise((_, reject) => {
          const t = setTimeout(() => reject(new Error('terminate wait timed out')), 5000);
          t.unref?.();
        }),
      ]);
      await worker.terminate();
    } catch {
      /* already gone — late orphan handled above */
    }
  }
}

export class OcrService {
  /** @param {Array} providers ordered; first available provider supporting the MIME wins */
  constructor(providers = null) {
    this.providers = providers || [new PlainTextOcrProvider(), new PdfTextOcrProvider(), new TesseractJsOcrProvider()];
  }

  async providerFor(mimeType) {
    for (const p of this.providers) {
      if (p.supports(mimeType) && (await p.isAvailable())) return p;
    }
    return null;
  }

  /**
   * Explains why no provider could handle `mimeType`, collecting each
   * candidate provider's own reason. Used to turn a dead end into
   * actionable guidance instead of a bare failure.
   */
  async diagnose(mimeType) {
    const reasons = [];
    for (const p of this.providers) {
      if (!p.supports(mimeType)) continue;
      const why = p.unavailabilityReason ? await p.unavailabilityReason() : null;
      reasons.push(`${p.name}: ${why || 'available'}`);
    }
    return reasons;
  }

  /**
   * @returns {{text, confidence, provider}} or throws OcrUnavailableError.
   */
  async extractText({ buffer, mimeType }) {
    if (!buffer || typeof mimeType !== 'string' || !mimeType) {
      throw new OcrUnavailableError(
        'Nothing readable was uploaded — paste the report text into the upload dialog, or try a photo of the report.',
      );
    }
    const provider = await this.providerFor(mimeType);
    if (!provider) {
      // Safety net for custom provider sets without a PDF handler — the
      // default set always includes PdfTextOcrProvider and fails more
      // specifically from inside extract().
      if (mimeType === 'application/pdf') {
        throw new OcrUnavailableError(
          `PDF files can't be read automatically here — open the PDF, copy its text, and paste it ` +
            `into the upload dialog (or add the values manually). Your report is saved and nothing is lost.`,
        );
      }
      const detail = (await this.diagnose(mimeType)).join('; ');
      throw new OcrUnavailableError(
        `No OCR provider available for '${mimeType}'. ` +
          (detail ? `[${detail}] ` : '') +
          `To read photo/image reports install language data with \`npm run ocr:setup\`, ` +
          `or paste the report text into the upload dialog.`,
      );
    }
    try {
      return await provider.extract({ buffer, mimeType });
    } catch (err) {
      // Providers must only ever surface actionable OCR errors — an unexpected
      // throw (worker bug, malformed payload) is normalized so the report
      // pipeline's ocr_failed path handles it instead of a 500.
      if (err instanceof OcrUnavailableError) throw err;
      const detail = typeof err === 'string' ? err : err?.message || String(err);
      throw new OcrUnavailableError(
        `Could not read text from this file (${detail}). Paste the report text into the upload dialog instead — your report is saved and nothing is lost.`,
      );
    }
  }

  /** Releases provider resources (cached Tesseract workers). */
  async close() {
    await Promise.all(this.providers.map((p) => (p.terminate ? p.terminate() : null)));
  }
}
