#!/usr/bin/env python3
"""
Compile-check the Android shell's Java without Gradle, without the SDK manager
and without network access.

The authoritative build is `gradle :app:assembleRelease` in CI. But a full
Gradle/AGP round trip needs the Android SDK, a JDK and a trip to Google's
Maven repository, and it takes ~40s to tell you that one symbol is missing.
This script answers the same question in about a second using only:

  * any `javac` (a real JDK 17 is ideal), or a JRE plus a JDK 8 `tools.jar`
  * an `android.jar` — from $ANDROID_HOME/platforms, or passed explicitly

It generates throwaway `R.java` / `BuildConfig.java` stubs from `res/` (the
same names `verify_resources.py` checks) and compiles every Java source in the
module against them.

    python3 android/tools/compile_check.py
    python3 android/tools/compile_check.py --android-jar /path/to/android.jar
    python3 android/tools/compile_check.py --javac /path/to/javac

Two fallbacks exist for locked-down machines; both print a loud warning:

  * If the newest `android.jar` available has class files newer than the
    compiler supports (an API 34 jar is Java 17 / class version 61, while a JDK 8
    `tools.jar` javac only reads up to 52), a throwaway copy is rewritten to
    class version 52. Only the version field changes; the API signatures that
    the compile actually checks are untouched.
  * The public SDK stubs do not expose `java.lang.invoke.LambdaMetafactory`
    (it is @hide on-device), and javac 8 needs it to desugar a lambda or method
    reference. A two-method compile-time shim is generated and prepended to the
    bootclasspath so lambdas resolve. On a real JDK 17 + AGP none of this is
    needed — D8 desugars lambdas itself.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ANDROID_DIR = HERE.parent
MODULE = ANDROID_DIR / "app"
SRC = MODULE / "src" / "main" / "java"
RES = MODULE / "src" / "main" / "res"

VALUE_KINDS = ("string", "color", "dimen", "style", "integer", "bool", "array", "plurals")
FILE_KINDS = ("drawable", "mipmap", "layout", "menu", "xml", "anim", "animator", "raw", "font")
PREFERRED_APIS = (34, 35, 36, 33, 32, 31, 30, 29, 28)


class Failure(Exception):
    pass


# --------------------------------------------------------------------------- #
# stub generation
# --------------------------------------------------------------------------- #
def collect_resource_symbols() -> dict[str, set[str]]:
    symbols: dict[str, set[str]] = {}

    def add(kind: str, name: str) -> None:
        symbols.setdefault(kind, set()).add(name.replace(".", "_"))

    for values_file in sorted(RES.glob("values*/*.xml")):
        text = values_file.read_text(encoding="utf-8")
        for kind in VALUE_KINDS:
            for name in re.findall(rf'<{kind}\s+name="([^"]+)"', text):
                add(kind, name)
    for kind in FILE_KINDS:
        for path in sorted(RES.glob(f"{kind}*/*")):
            if path.is_file():
                add(kind, path.stem)
    for path in sorted(RES.glob("layout*/*.xml")) + sorted(RES.glob("menu*/*.xml")):
        for name in re.findall(r'android:id="@\+id/([^"]+)"', path.read_text(encoding="utf-8")):
            add("id", name)
    return symbols


def write_stubs(work: Path) -> list[Path]:
    symbols = collect_resource_symbols()
    package_dir = work / "ai" / "kivo"
    package_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "package ai.kivo.app;",
        "",
        "/* Throwaway stub generated by android/tools/compile_check.py.",
        "   AGP generates the real R from the AAPT2 symbol table. */",
        "public final class R {",
        "    private R() {}",
    ]
    counter = 0
    for kind in sorted(symbols):
        lines.append(f"    public static final class {kind} {{")
        lines.append(f"        private {kind}() {{}}")
        for name in sorted(symbols[kind]):
            counter += 1
            lines.append(f"        public static final int {name} = 0x7F{counter:06X};")
        lines.append("    }")
    lines.append("}")
    r_java = package_dir / "R.java"
    r_java.write_text("\n".join(lines) + "\n", encoding="utf-8")

    build_config = package_dir / "BuildConfig.java"
    build_config.write_text(
        "package ai.kivo.app;\n\n"
        "/* Throwaway stub generated by android/tools/compile_check.py. */\n"
        "public final class BuildConfig {\n"
        "    private BuildConfig() {}\n"
        "    public static final boolean DEBUG = false;\n"
        '    public static final String LIBRARY_PACKAGE_NAME = "ai.kivo.app";\n'
        '    public static final String APPLICATION_ID = "ai.kivo.app";\n'
        '    public static final String BUILD_TYPE = "release";\n'
        '    public static final String VERSION_NAME = "0.0.0";\n'
        "    public static final int VERSION_CODE = 0;\n"
        "}\n",
        encoding="utf-8",
    )
    total = sum(len(v) for v in symbols.values())
    print(f"[compile] generated stubs: R.java ({total} symbols in {len(symbols)} kinds) + BuildConfig.java")
    return [r_java, build_config]


# --------------------------------------------------------------------------- #
# toolchain discovery
# --------------------------------------------------------------------------- #
def find_javac(explicit: str | None) -> tuple[list[str], int]:
    """Returns (command prefix, supported class-file major version)."""
    candidates: list[list[str]] = []
    if explicit:
        candidates.append([explicit])
    if os.environ.get("JAVA_HOME"):
        candidates.append([str(Path(os.environ["JAVA_HOME"]) / "bin" / "javac")])
    found = shutil.which("javac")
    if found:
        candidates.append([found])
    # A JRE plus a JDK 8 tools.jar can still compile: javac 8 lives inside it.
    tools_jar = os.environ.get("JAVA_TOOLS_JAR")
    for jar in [tools_jar] if tools_jar else []:
        java = shutil.which("java")
        if java and Path(jar).exists():
            candidates.append([java, "-cp", jar, "com.sun.tools.javac.Main"])

    for command in candidates:
        try:
            probe = subprocess.run([*command, "-version"], capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.SubprocessError):
            continue
        text = f"{probe.stdout} {probe.stderr}"
        match = re.search(r"javac\s+(\d+)(?:\.(\d+))?", text)
        if not match:
            continue
        feature = int(match.group(1))
        legacy = int(match.group(2) or 0)
        # javac 1.8 reports "1.8.0_131"; javac 17 reports "17.0.9"
        version = legacy if feature == 1 else feature
        print(f"[compile] using: {' '.join(command)}  (javac {text.strip()})")
        return command, 44 + version   # Java 8 -> class file 52, Java 17 -> 61
    raise Failure(
        "no usable javac found. Install a JDK 17+, set JAVA_HOME, pass --javac, "
        "or set JAVA_TOOLS_JAR to a JDK 8 tools.jar next to a `java` on PATH."
    )


def find_android_jar(explicit: str | None) -> Path:
    if explicit:
        path = Path(explicit)
        if not path.exists():
            raise Failure(f"--android-jar does not exist: {path}")
        return path
    roots = [os.environ.get(k) for k in ("ANDROID_HOME", "ANDROID_SDK_ROOT")]
    for root in roots:
        if not root:
            continue
        platforms = Path(root) / "platforms"
        for api in PREFERRED_APIS:
            candidate = platforms / f"android-{api}" / "android.jar"
            if candidate.exists():
                return candidate
        for candidate in sorted(platforms.glob("android-*/android.jar"), reverse=True):
            return candidate
    raise Failure(
        "no android.jar found. Set ANDROID_HOME (the SDK's platforms/android-34/android.jar "
        "is what the build uses) or pass --android-jar /path/to/android.jar."
    )


def jar_class_version(jar: Path) -> int:
    with zipfile.ZipFile(jar) as archive:
        for name in archive.namelist():
            if name.endswith(".class"):
                head = archive.read(name)[:8]
                if head[:4] == b"\xca\xfe\xba\xbe":
                    return struct.unpack(">H", head[6:8])[0]
    return 0


def downgrade_jar(jar: Path, target: int, work: Path) -> Path:
    """Rewrite a copy of the jar so an older javac can read the stub classes."""
    out = work / "android-downgraded.jar"
    changed = 0
    with zipfile.ZipFile(jar) as source, zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as dest:
        for item in source.infolist():
            data = source.read(item.filename)
            if item.filename.endswith(".class") and data[:4] == b"\xca\xfe\xba\xbe":
                major = struct.unpack(">H", data[6:8])[0]
                if major > target:
                    data = data[:4] + struct.pack(">HH", 0, target) + data[8:]
                    changed += 1
            dest.writestr(item.filename, data)
    print(f"[compile] WARNING: rewrote {changed} class files in a throwaway copy of {jar.name} "
          f"to class version {target} so this compiler can read them.")
    print("[compile]          Signatures are unchanged; the authoritative build is still Gradle/AGP in CI.")
    return out


LAMBDA_SHIM = """package java.lang.invoke;

/* Generated by android/tools/compile_check.py: the public SDK stubs hide
   LambdaMetafactory, and javac 8 needs it to desugar lambdas. Compile-time only. */
public class LambdaMetafactory {
    public static CallSite metafactory(MethodHandles.Lookup caller, String interfaceMethodName,
            MethodType factoryType, MethodType interfaceMethodType, MethodHandle implementation,
            MethodType dynamicMethodType) throws LambdaConversionException {
        throw new LambdaConversionException("compile-time shim");
    }

    public static CallSite altMetafactory(MethodHandles.Lookup caller, String interfaceMethodName,
            MethodType factoryType, Object... args) throws LambdaConversionException {
        throw new LambdaConversionException("compile-time shim");
    }
}
"""


def build_lambda_shim(javac: list[str], bootclasspath: str, work: Path) -> Path | None:
    """Only needed for javac 8, which desugars lambdas at compile time."""
    source_dir = work / "shim-src" / "java" / "lang" / "invoke"
    source_dir.mkdir(parents=True, exist_ok=True)
    source = source_dir / "LambdaMetafactory.java"
    source.write_text(LAMBDA_SHIM, encoding="utf-8")
    classes = work / "shim-classes"
    classes.mkdir(parents=True, exist_ok=True)
    probe = subprocess.run(
        [*javac, "-source", "1.8", "-target", "1.8", "-nowarn", "-XDignore.symbol.file",
         "-bootclasspath", bootclasspath, "-d", str(classes), str(source)],
        capture_output=True, text=True,
    )
    if probe.returncode != 0:
        return None
    shim = work / "lambda-shim.jar"
    with zipfile.ZipFile(shim, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in classes.rglob("*.class"):
            archive.write(path, path.relative_to(classes).as_posix())
    print("[compile] WARNING: added a java.lang.invoke.LambdaMetafactory shim so javac 8 can")
    print("[compile]          desugar lambdas (the SDK stubs hide that class). Compile-time only;")
    print("[compile]          AGP/D8 do not need it.")
    return shim


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Compile-check the kivo Android shell's Java.")
    parser.add_argument("--android-jar", help="path to android.jar (default: from ANDROID_HOME)")
    parser.add_argument("--javac", help="javac binary (default: JAVA_HOME/bin/javac or PATH)")
    parser.add_argument("--release", default="17", help="source/target level (default 17)")
    parser.add_argument("--keep", action="store_true", help="keep the temp directory and print it")
    args = parser.parse_args(argv[1:])

    if not SRC.is_dir():
        print(f"[compile] no Java sources at {SRC}", file=sys.stderr)
        return 1

    work = Path(tempfile.mkdtemp(prefix="kivo-compile-"))
    try:
        sources = sorted(SRC.rglob("*.java"))
        if not sources:
            print("[compile] nothing to compile")
            return 0
        print(f"[compile] {len(sources)} source file(s) in {SRC.relative_to(ANDROID_DIR.parent)}")

        try:
            javac, class_version = find_javac(args.javac)
            android_jar = find_android_jar(args.android_jar)
        except Failure as failure:
            print(f"[compile] SKIPPED — {failure}")
            return 0  # a missing local toolchain is not a code defect

        print(f"[compile] android.jar: {android_jar}")
        bootclasspath = str(android_jar)
        jar_version = jar_class_version(android_jar)
        if jar_version > class_version:
            android_jar = downgrade_jar(android_jar, class_version, work)
            bootclasspath = str(android_jar)

        legacy = class_version <= 52
        level = "1.8" if legacy else args.release
        if legacy:
            shim = build_lambda_shim(javac, bootclasspath, work)
            if shim:
                bootclasspath = f"{shim}{os.pathsep}{bootclasspath}"

        stubs = write_stubs(work)
        out = work / "classes"
        out.mkdir(exist_ok=True)
        # javac 8 takes the platform as -bootclasspath; javac 9+ rejects that
        # flag for modern -source levels, so the android.jar goes on the regular
        # classpath instead (java.* then resolves from the JDK, android.* from
        # the jar — which is all a type check needs).
        platform_args = (["-bootclasspath", bootclasspath] if legacy
                         else ["-classpath", bootclasspath])
        command = [
            *javac,
            "-source", level, "-target", level,
            "-encoding", "UTF-8",
            "-nowarn" if legacy else "-Xlint:all,-deprecation,-serial,-options",
            "-XDignore.symbol.file",
            *platform_args,
            "-d", str(out),
            *[str(path) for path in sources + stubs],
        ]
        print(f"[compile] javac -source {level} … ({len(sources) + len(stubs)} files)")
        result = subprocess.run(command, capture_output=True, text=True)
        output = f"{result.stdout}\n{result.stderr}".strip()

        errors = [line for line in output.splitlines() if " error:" in line or line.startswith("error:")]
        if result.returncode == 0 and not errors:
            produced = sorted(p.name for p in out.rglob("*.class"))
            print(f"[compile] OK — compiled cleanly, {len(produced)} class file(s): {', '.join(produced[:8])}"
                  + (" …" if len(produced) > 8 else ""))
            if output:
                print("[compile] compiler notes:")
                for line in output.splitlines()[:20]:
                    print(f"          {line}")
            return 0

        print(f"[compile] FAILED — {len(errors) or 'unknown number of'} compile error(s):\n", file=sys.stderr)
        print(output[:8000], file=sys.stderr)
        return 1
    finally:
        if args.keep:
            print(f"[compile] temp dir kept: {work}")
        else:
            shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
